### ISSUE TITLE
ValueError("Need either a `state_dict` or a `save_folder` containing offloaded weights.")

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [OpenCodeInterpreter/OpenCodeInterpreter#15]
When I run the demo code, the following error occurs.
How do I fix it so it works?

```bash
root@2964f02546c4:/app/demo# python3 chatbot.py --path  m-a-p/OpenCodeInterpreter-DS-6.7B
>>>> model_path:m-a-p/OpenCodeInterpreter-DS-6.7B
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpw04u_i4o
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpw04u_i4o/_remote_module_non_scriptable.py
[2024-03-04 14:28:32,267] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:55<00:00, 27.91s/it]
Traceback (most recent call last):
  File "/app/demo/chatbot.py", line 318, in <module>
    gradio_launch(model_path=args.path)
  File "/app/demo/chatbot.py", line 294, in gradio_launch
    interpreter = StreamingOpenCodeInterpreter(model_path=model_path)
  File "/app/demo/code_interpreter/OpenCodeInterpreter.py", line 43, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3919, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 364, in dispatch_model
    weights_map = OffloadedWeightsLoader(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/offload.py", line 150, in __init__
    raise ValueError("Need either a `state_dict` or a `save_folder` containing offloaded weights.")
ValueError: Need either a `state_dict` or a `save_folder` containing offloaded weights.
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fd1e9cb4f10>
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fd1dbe06050>
root@2964f02546c4:/app/demo# [IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

**Comment by Sunwood-ai-labs** [comment]
thank you！！
The problem was successfully resolved
