### ISSUE TITLE
ValueError: You are trying to offload the whole model to the disk. Please use the `disk_offload` function instead.

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [OpenCodeInterpreter/OpenCodeInterpreter#18]
When I run the demo code, the following error occurs.
How do I fix it so it works?

＊I am using offload as per the answer here
https://github.com/OpenCodeInterpreter/OpenCodeInterpreter/issues/15

## Code

```
        print(f">>>> model_path:{model_path}")
        # build tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_path,
            padding_side="right",
            trust_remote_code=True
        )

        self.model = AutoModelForCausalLM.from_pretrained(
            model_path,
            device_map="auto",
            load_in_4bit=load_in_4bit,
            load_in_8bit=load_in_8bit,
            torch_dtype=torch.float16,
            trust_remote_code=True,
            offload_folder="save_folder"
        )
```

## error
```
root@2964f02546c4:/app/demo# python3 chatbot.py --path  "m-a-p/OpenCodeInterpreter-DS-6.7B"
>>>> model_path:m-a-p/OpenCodeInterpreter-DS-6.7B
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp1dop96a9
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp1dop96a9/_remote_module_non_scriptable.py
[2024-03-07 15:08:37,741] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 94254.02it/s]
Traceback (most recent call last):
  File "/app/demo/chatbot.py", line 318, in <module>
    gradio_launch(model_path=args.path)
  File "/app/demo/chatbot.py", line 294, in gradio_launch
    interpreter = StreamingOpenCodeInterpreter(model_path=model_path)
  File "/app/demo/code_interpreter/OpenCodeInterpreter.py", line 42, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3919, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 387, in dispatch_model
    raise ValueError(
ValueError: You are trying to offload the whole model to the disk. Please use the `disk_offload` function instead.
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7f03125e1090>
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7f0310a0e0b0>
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
root@2964f02546c4:/app/demo# [IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

**Comment by tariksghiouri** [comment]
did you find the source of the issue or not yet?
